[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
fs_permissions = [
    { access = "read", path = "./test/bin" },
    { access = "read", path = "./out" },
    { access = "read", path = "./test/test_data" },
]
remappings = [
    "@forge-std/=dependencies/forge-std-1.9.7/src",
    "@licredity-v1-core/=dependencies/licredity-v1-core-1.0.0/src",
    "@licredity-v1-test/=dependencies/licredity-v1-core-1.0.0/test",
    "@uniswap-v4-core/=dependencies/uniswap-v4-core-4/src",
]

[dependencies]
forge-std = "1.9.7"
uniswap-v4-core = "4"
licredity-v1-core = { version = "1.0.0", git = "git@github.com:Licredity/licredity-v1-core.git", rev = "613967aa5b6301834062c96f7eb2678fa8544f0b" }

[rpc_endpoints]
ETH = "${ETH_RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
